// RUN: qcc-opt %s -convert-qvec-to-hisepq-intrinsics=min-vlen=128 --split-input-file | FileCheck %s

// The two qubits have to occupy the two front entries of an otherwise poison
// `vector<[N]xi8>`. Poison means "we don't care".

// CHECK-LABEL: func.func @single_gates
func.func @single_gates() {
    %q0 = qco.static 0 : !qco.qubit
    %q1 = qco.static 1 : !qco.qubit
    %q2 = qco.static 2 : !qco.qubit
    %qs = vector.from_elements %q0, %q1, %q2 : vector<3x!qco.qubit>

    %h = qvec.single h %qs : vector<3x!qco.qubit>
    %x = qvec.single x %h : vector<3x!qco.qubit>

    func.return
}

// CHECK-NOT:     qco.static
// CHECK-NOT:     vector.from_elements
// CHECK-DAG:     %[[VL:.*]] = llvm.mlir.constant(3 : i32) : i32
// CHECK-DAG:     %[[ZERO:.*]] = llvm.mlir.constant(0 : i32) : i32

// Create and insert a vector of three qubits at the front of a scalable vector `vector<[2]xi8>`
// which can hold up to 4 elements at vscale = 2 = VLEN / 64.
// Elements 3 and above contain poison values, meaning that using those in a computation is
// undefined behavior - right for us.
// CHECK-DAG:     %[[IDX:.*]] = llvm.mlir.constant(dense<[0, 1, 2]> : vector<3xi8>) : vector<3xi8>
// CHECK-DAG:     %[[POISON:.*]] = llvm.mlir.poison : vector<[2]xi8>
// CHECK:         %[[V0:.*]] = llvm.intr.vector.insert %[[IDX]], %[[POISON]][0] : vector<3xi8> into vector<[2]xi8>

// The `x` names the same three qubits as the `h`, because it consumes the vector the `h` returned.
// CHECK:         llvm.call_intrinsic "llvm.riscv.qv.h"(%[[V0]], %[[ZERO]], %[[ZERO]], %[[VL]])
// CHECK:         %[[V1:.*]] = llvm.intr.vector.insert %[[IDX]], %[[POISON]][0] : vector<3xi8> into vector<[2]xi8>
// CHECK:         llvm.call_intrinsic "llvm.riscv.qv.x"(%[[V1]], %[[ZERO]], %[[ZERO]], %[[VL]])

// -----

// The encoding is `qv.cx vs1(ctrl), vs2(tgt)`, the same order `qvec.pair` reads, so the two
// operands pass through unswapped.

// CHECK-LABEL: func.func @pair_gates
func.func @pair_gates() {
    %c0 = qco.static 0 : !qco.qubit
    %c1 = qco.static 1 : !qco.qubit
    %ctrls = vector.from_elements %c0, %c1 : vector<2x!qco.qubit>

    %t0 = qco.static 2 : !qco.qubit
    %t1 = qco.static 3 : !qco.qubit
    %tgts = vector.from_elements %t0, %t1 : vector<2x!qco.qubit>

    %ctrls_out, %tgts_out = qvec.pair cx %ctrls, %tgts : vector<2x!qco.qubit>

    func.return
}

// CHECK-DAG:     %[[CTRL_IDX:.*]] = llvm.mlir.constant(dense<[0, 1]> : vector<2xi8>) : vector<2xi8>
// CHECK-DAG:     %[[TGT_IDX:.*]] = llvm.mlir.constant(dense<[2, 3]> : vector<2xi8>) : vector<2xi8>
// CHECK-DAG:     %[[CTRLS:.*]] = llvm.intr.vector.insert %[[CTRL_IDX]], %{{.*}}[0]
// CHECK-DAG:     %[[TGTS:.*]] = llvm.intr.vector.insert %[[TGT_IDX]], %{{.*}}[0]
// CHECK:         llvm.call_intrinsic "llvm.riscv.qv.cx"(%[[CTRLS]], %[[TGTS]], %{{.*}}, %{{.*}})


// -----

// TODO: Currently the QISA does not provide the measurement result to us. Here we replace it by poison. Needs fixing
// upstream ASAP.

// CHECK-LABEL: func.func @measurement
func.func @measurement() -> vector<2xi1> {
    %q0 = qco.static 0 : !qco.qubit
    %q1 = qco.static 1 : !qco.qubit
    %qs = vector.from_elements %q0, %q1 : vector<2x!qco.qubit>

    %qs_out, %result = qvec.mz %qs : vector<2x!qco.qubit> -> vector<2xi1>

    func.return %result : vector<2xi1>
}

// CHECK-NOT:     qvec.mz
// CHECK:         %[[RES:.*]] = llvm.mlir.poison : vector<2xi1>
// CHECK:         llvm.call_intrinsic "llvm.riscv.qv.mz"(%{{.*}}, %{{.*}}, %{{.*}}, %{{.*}})
// CHECK:         return %[[RES]] : vector<2xi1>

// -----

// CHECK-LABEL: func.func @threaded
func.func @threaded() -> vector<2xi1> {
    %c0 = qco.static 0 : !qco.qubit
    %c1 = qco.static 1 : !qco.qubit
    %ctrls = vector.from_elements %c0, %c1 : vector<2x!qco.qubit>

    %t0 = qco.static 2 : !qco.qubit
    %t1 = qco.static 3 : !qco.qubit
    %tgts = vector.from_elements %t0, %t1 : vector<2x!qco.qubit>

    %h = qvec.single h %ctrls : vector<2x!qco.qubit>
    %ctrls_out, %tgts_out = qvec.pair cx %h, %tgts : vector<2x!qco.qubit>
    %mq, %bits = qvec.mz %ctrls_out : vector<2x!qco.qubit> -> vector<2xi1>
    %x = qvec.single x %mq : vector<2x!qco.qubit>

    func.return %bits : vector<2xi1>
}

// CHECK-NOT:     qvec.
// CHECK-DAG:     %[[CTRL_IDX:.*]] = llvm.mlir.constant(dense<[0, 1]> : vector<2xi8>) : vector<2xi8>
// CHECK-DAG:     %[[TGT_IDX:.*]] = llvm.mlir.constant(dense<[2, 3]> : vector<2xi8>) : vector<2xi8>

// Every instruction addresses the controls, except the `cx`, which addresses both.
// CHECK:         llvm.intr.vector.insert %[[CTRL_IDX]]
// CHECK:         llvm.call_intrinsic "llvm.riscv.qv.h"
// CHECK-DAG:     %[[CX_TGTS:.*]] = llvm.intr.vector.insert %[[TGT_IDX]]
// CHECK-DAG:     %[[CX_CTRLS:.*]] = llvm.intr.vector.insert %[[CTRL_IDX]]
// CHECK:         llvm.call_intrinsic "llvm.riscv.qv.cx"(%[[CX_CTRLS]], %[[CX_TGTS]], %{{.*}}, %{{.*}})
// CHECK:         llvm.intr.vector.insert %[[CTRL_IDX]]
// CHECK:         llvm.call_intrinsic "llvm.riscv.qv.mz"
// CHECK:         llvm.intr.vector.insert %[[CTRL_IDX]]
// CHECK:         llvm.call_intrinsic "llvm.riscv.qv.x"

// -----

// CHECK-LABEL: func.func @sparse_qubit_indices
func.func @sparse_qubit_indices() {
    %q0 = qco.static 7 : !qco.qubit
    %q1 = qco.static 3 : !qco.qubit
    %q2 = qco.static 255 : !qco.qubit
    %qs = vector.from_elements %q0, %q1, %q2 : vector<3x!qco.qubit>

    %h = qvec.single h %qs : vector<3x!qco.qubit>

    func.return
}

// NOTE: 255 == -1; just a printing quirk.
// CHECK:         llvm.mlir.constant(dense<[7, 3, -1]> : vector<3xi8>) : vector<3xi8>
// CHECK:         llvm.call_intrinsic "llvm.riscv.qv.h"

// -----

// Output recording has no QISA counterpart, so it goes and the program reports nothing back.

// CHECK-LABEL: func.func @output_recording
func.func @output_recording(%value: i64, %buffer: memref<4xi1>) {
    %q0 = qco.static 0 : !qco.qubit
    %qs = vector.from_elements %q0 : vector<1x!qco.qubit>
    %mz, %bits = qvec.mz %qs : vector<1x!qco.qubit> -> vector<1xi1>

    aux.record_int %value : i64
    aux.record_memref %buffer : memref<4xi1>

    func.return
}

// CHECK:         llvm.call_intrinsic "llvm.riscv.qv.mz"
// CHECK-NOT:     aux.record
